
////
This file is generated! See _meta/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
= Exported Fields

[partintro]

--
This document describes the fields that are exported by Rmqbeat. They are
grouped in the following categories:

* <<exported-fields-beat>>
* <<exported-fields-cloud>>
* <<exported-fields-rmqbeat>>

--
[[exported-fields-beat]]
== Beat Fields

Contains common beat fields available in all event types.



[float]
=== beat.name

The name of the Beat sending the log messages. If the Beat name is set in the configuration file, then that value is used. If it is not set, the hostname is used. To set the Beat name, use the `name` option in the configuration file.


[float]
=== beat.hostname

The hostname as returned by the operating system on which the Beat is running.


[float]
=== beat.version

The version of the beat that generated this event.


[float]
=== @timestamp

type: date

example: August 26th 2016, 12:35:53.332

format: date

required: True

The timestamp when the event log record was generated.


[float]
=== tags

Arbitrary tags that can be set per Beat and per transaction type.


[float]
=== fields

type: dict

Contains user configurable fields.


[[exported-fields-cloud]]
== Cloud Provider Metadata Fields

Metadata from cloud providers added by the add_cloud_metadata processor.



[float]
=== meta.cloud.provider

example: ec2

Name of the cloud provider. Possible values are ec2, gce, or digitalocean.


[float]
=== meta.cloud.instance_id

Instance ID of the host machine.


[float]
=== meta.cloud.machine_type

example: t2.medium

Machine type of the host machine.


[float]
=== meta.cloud.availability_zone

example: us-east-1c

Availability zone in which this host is running.


[float]
=== meta.cloud.project_id

example: project-x

Name of the project in Google Cloud.


[float]
=== meta.cloud.region

Region in which this host is running.


[[exported-fields-rmqbeat]]
== rmqbeat Fields

None


[float]
== rabbitmq Fields

RabbitMQ Message Metadata.



[float]
=== rabbitmq.action

type: keyword

required: False

For tracing either 'publish' or 'deliver'. For normal consumer always 'receive'.


[float]
=== rabbitmq.channel

type: long

required: False

Channel number of the client which performed action (trace only).


[float]
=== rabbitmq.connection

type: keyword

required: False

Connection name of the client which performed action (trace only).


[float]
=== rabbitmq.user

type: keyword

required: False

User that performed the action (trace only).


[float]
=== rabbitmq.consumer_tag

type: keyword

Consumer tag (direct consume only).


[float]
== headers Fields

Message header field table.


[float]
=== rabbitmq.exchange

type: text

required: False

Specifies the name of the exchange that the message was originally published to. May be empty, indicating the default exchange.


[float]
=== rabbitmq.queue

type: text

required: False

Specifies the name of the queue message was consumed from (tracer only).


[float]
=== rabbitmq.routed_queues

type: list

required: False

Specifies names of queues message was routed to (tracer only).


[float]
=== rabbitmq.redelivered

type: boolean

required: False

Specifies if message was redelivered.


[float]
=== rabbitmq.routing_key

type: text

required: False

Specifies the routing key name specified when the message was published.


[float]
== payload Fields

Payload Information



[float]
=== rabbitmq.payload.size

type: long

required: True

Size of payload in bytes


[float]
=== rabbitmq.payload.body

type: text

required: False

Decoded payload body


[float]
== properties Fields

AMQP message properties.



[float]
=== rabbitmq.properties.app_id

type: keyword

required: False

Creating application id.


[float]
=== rabbitmq.properties.content_encoding

type: keyword

required: False

MIME content encoding.


[float]
=== rabbitmq.properties.content_type

type: keyword

required: False

MIME content type.


[float]
=== rabbitmq.properties.correlation_id

type: keyword

required: False

Application correlation identifier.


[float]
=== rabbitmq.properties.delivery_mode

type: keyword

required: False

Non-persistent (1) or persistent (2).


[float]
=== rabbitmq.properties.expiration

required: False

Message expiration specification.


[float]
=== rabbitmq.properties.message_id

type: keyword

required: False

Application message identifier.


[float]
=== rabbitmq.properties.priority

type: keyword

required: False

Message priority, 0 to 9.


[float]
=== rabbitmq.properties.reply_to

type: text

required: False

Address to reply to.


[float]
=== rabbitmq.properties.timestamp

type: date

required: False

Message timestamp.


[float]
=== rabbitmq.properties.type

type: keyword

required: False

Message type name.


[float]
=== rabbitmq.properties.user_id

type: keyword

required: False

Creating user id.


